### ISSUE TITLE
Python version installation. 

### ISSUE THREAD

**Issue by mharris2018** [learn-co-curriculum/multiphase-macos-env-python#3]
### Canvas Link

https://learning.flatironschool.com/courses/6796/pages/installing-python-on-macos?module_item_id=551147

### Concern

I am working on installing python 3.8.13. I have gone through the steps and it will read 3.9.6 has been installed. Is it ok to move forward with this version or should I make sure I have 3.8.13 stalled? 
[python installation.docx](https://github.com/learn-co-curriculum/multiphase-macos-env-python/files/11262057/python.installation.docx)

**Comment by lizbur10** [comment]
Hello - it looks like this issue is probably outdated by now so I'm going to go ahead and close it. Hope you got it worked out! 💙
